### ISSUE TITLE
HttpOnly flag not set on XSRF-TOKEN cookie

### ISSUE THREAD

**Issue by jrdioko** [jsanders/angular_rails_csrf#29]
The OWASP ZAP security scanner alerts on the `XSRF-TOKEN` cookie, saying, "Ensure that the `HttpOnly` flag is set for all cookies." Could `angular_rails_csrf` set the `HttpOnly` flag on the token cookie?

**Comment by bodrovis** [comment]
I will research it a bit more. I wonder whether it will cause any unwanted side effects...

**Comment by bodrovis** [comment]
All in all, I do not think it is a good idea to add such flag. As mentioned here https://www.owasp.org/index.php/HttpOnly#Browsers_Supporting_HttpOnly, "a client side script will be unable to read or write the session cookie". That's indeed bad because the whole purpose of the gem is to set the session cookie so that later the script *can* read it.

Let me know, if I am missing something.

**Comment by jrdioko** [comment]
My apologies, it looks like I misunderstood what was going on here.

**Comment by bodrovis** [comment]
No problems!
