### ISSUE TITLE
Consider catching invalid authenticity token exception

### ISSUE THREAD

**Issue by PaulL1** [jsanders/angular_rails_csrf#4]
I've been working further on CSRF from when this was originally created - it's been giving intermittent grief in my application.  The problem is the interactions between Devise, AngularJS and Rails.  Blog post here: http://technpol.wordpress.com/2014/04/17/rails4-angularjs-csrf-and-devise/

Most of the solutions I have relate more specifically to Devise, however one element might be relevant to this Gem.

When Rails returns an invalid authenticity token exception it doesn't call a render action, and therefore doesn't reset the cookie.  The user experience would probably be better in most apps by sending a new cookie in that situation.  The code I use to do that is:

```
rescue_from ActionController::InvalidAuthenticityToken do |exception|
  cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  render :error => 'invalid token', {:status => :unprocessable_entity}
end
```

It's not clear to me whether this is a problem that it would make sense to resolve within this gem, but worth considering.

**Comment by jsanders** [comment]
@PaulL1: I know this is quite old now, but I've just re-read your blog post and given it another think.

So the issue seems to be that leaving the `XSRF-TOKEN` cookie around after the session it's associated with has gone away could confuse clients that think they have a valid value to send in the `X-XSRF-TOKEN` header, when in fact it is no longer valid. However, if I'm understanding correctly, the problem would be rectified as soon as the next `GET` request is sent, because it would generate a new session with a valid `XSRF-TOKEN` cookie, which would then be used for future non-`GET`s.

I don't think this is so bad, because of `GET`s breaking the cycle, but it does seem messy and confusing to have an invalid cookie floating around. I'm wondering if the right approach would be to unset the `XSRF-TOKEN` cookie any time `reset_session` (which I believe all the session-management libraries use) is called. I'll look into that a bit.

**Comment by PaulL1** [comment]
Yeah, that could help, it's been a while since I played with it (and I still have some occasional CSRF issues that I need to fix still).  My real problem was that I'm using rails as an API on the back end, and so I frequently get parallel requests from different threads, and have a thread race condition issue with my CSRF - even if one request returns a new cookie (or invalidates the cookie) it doesn't mean I wouldn't have other requests in parallel coming in still with the old cookie.

I think it's tidier to explicitly invalidate the cookie if it's invalidate (makes sense), but it's not all of the solution.

**Comment by bodrovis** [comment]
Anyone who wishes to ponder this is very much welcome. Until then, closing this one.
